module TraceurWorker {
	importScripts("/assets/javascripts/traceur.js");
	importScripts("/assets/javascripts/source-map.js");
	
	self.onmessage = function(m) {
		var index: number;
		var value: any;
		
		try {
			// Create a Traceur compiler with correct settings
			var compiler = new traceur.Compiler(m.data.config);
			var filename = m.data.filename;
			
			// Compile the source code
			value = compiler.compile(m.data.source, filename);
			index = 0;
			
			// Fetch source maps generated by TypeScript and Traceur
			var ts_map_str = m.data.config.tsSourceMap;
			var traceur_map_str = compiler.sourceMapCache_;
			
			// If both are available, compute map from Traceur-generated to Typescript-source
			if (ts_map_str && traceur_map_str) {
				// Load both source maps
				var ts_map = new sourceMap.SourceMapConsumer(ts_map_str);
				var traceur_map = new sourceMap.SourceMapConsumer(traceur_map_str);
				
				// Construct a blank one
				var gen = new sourceMap.SourceMapGenerator({
					file: filename
				});
				
				// For each mapping in the Typescript source map find the
				// corresponding mapping in the Traceur one and add it
				ts_map.eachMapping(function(mapping) {
					traceur_map.allGeneratedPositionsFor({
						source: filename,
						line: mapping.generatedLine,
						column: mapping.generatedColumn
					}).forEach(function(m: any) {
						gen.addMapping({
							source: mapping.source,
							original: { line: mapping.originalLine, column: mapping.originalColumn },
							generated: m
						});
					});
				});
				
				// Replace the serialized source map in the generated code
				value = value.replace(/(sourceMappingURL=data:application\/json;base64,)[^\n]+/, "$1" + btoa(gen.toString()));
			}
		} catch(e) {
			value = e[0];
			index = 1;
			console.error(e);
		}
		
		self.postMessage({
			rid: m.data.rid,
			index: index,
			value: value
		}, void 0);
	};
}
